name: Generate new version

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Version increment"
        required: true
        default: patch
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      npmVersion: ${{ steps.tagGen.outputs.new_version }}
      changelog: ${{ steps.tagGen.outputs.changelog }}
    steps:
      - uses: step-security/harden-runner@v1.4.5
        with:
          egress-policy: audit
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Git
        run: |
          git config user.name "NodeRT[bot]"
          git config user.email "nodertbot@demosjarco.dev"
      - uses: crazy-max/ghaction-import-gpg@v5.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - name: Bump version
        id: tagGen
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ inputs.semver }}
          release_branches: ${{  github.ref_name }}
          dry_run: true
      - name: Create tag
        run: git tag ${{ steps.tagGen.outputs.new_tag }}
      - name: Push tag
        run: git push origin --tags