on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Version increment"
        required: true
        default: patch
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3